#! /usr/bin/env python
import sys
import os

# Package path setup
package_base = \
os.path.realpath(os.path.join(os.path.dirname(sys.argv[0]), ".."))
sys.path.append(os.path.join(package_base, "python"))

from xslcover import config
from xslcover import xslcoverage

# Package configuration
config.set_config(xslcover_path=os.path.join(package_base, "java"))

xslcoverage.main()
